
# -*- coding: utf-8 -*-
"""mnist_vae.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ir0QyyXZwz1qMr2E49clH9hrQGNOFpAR
"""

### Variational Autoencoder
import torch
import torch.nn as nn

# VAE Model Hyperparameters
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu' #torch.device("cuda" if cuda else "cpu")
print(DEVICE)
num_classes = 10
batch_size = 60

x_dim  = 3072
hidden_dim1 = 1500
hidden_dim2 = 600
latent_dim = 128

lr = 1e-3
epochs = 100
# train_on_gpu = torch.cuda.is_available()
# print(train_on_gpu)

# Encoder

class Encoder(nn.Module):
    
    def __init__(self, input_dim, hidden_dim1, hidden_dim2, latent_dim):
        super(Encoder, self).__init__()

        self.FC_input = nn.Linear(input_dim, hidden_dim1)
        self.FC_input2 = nn.Linear(hidden_dim1, hidden_dim2)
        # self.FC_input3 = nn.Linear(hidden_dim2, hidden_dim2)
        self.FC_mean  = nn.Linear(hidden_dim2, latent_dim)
        self.FC_var   = nn.Linear (hidden_dim2, latent_dim)
        
        self.LeakyReLU = nn.LeakyReLU(0.2)
        
        self.training = True
        
    def forward(self, x):
        h_       = self.LeakyReLU(self.FC_input(x))
        h_       = self.LeakyReLU(self.FC_input2(h_))
        # h_       = self.LeakyReLU(self.FC_input3(h_))
        mean     = self.FC_mean(h_)
        log_var  = self.FC_var(h_)                     # encoder produces mean and log of variance 
                                                       #             (i.e., parateters of simple tractable normal distribution "q"
        
        return mean, log_var

# Decoder

class Decoder(nn.Module):
    def __init__(self, latent_dim, hidden_dim1,hidden_dim2, output_dim):
        super(Decoder, self).__init__()
        self.FC_hidden = nn.Linear(latent_dim, hidden_dim2)
        self.FC_hidden2 = nn.Linear(hidden_dim2, hidden_dim1)
        # self.FC_hidden3 = nn.Linear(hidden_dim1, hidden_dim1)
        self.FC_output = nn.Linear(hidden_dim1, output_dim)
        
        self.LeakyReLU = nn.LeakyReLU(0.2)
        
    def forward(self, x):
        h     = self.LeakyReLU(self.FC_hidden(x))
        h     = self.LeakyReLU(self.FC_hidden2(h))
        # h     = self.LeakyReLU(self.FC_hidden3(h))

        x_hat = torch.sigmoid(self.FC_output(h))
        return x_hat

class Model(nn.Module):
    def __init__(self, Encoder, Decoder):
        super(Model, self).__init__()
        self.Encoder = Encoder
        self.Decoder = Decoder
        
    def reparameterization(self, mean, var):
        epsilon = torch.randn_like(var).to(DEVICE)        # sampling epsilon        
        z = mean + var*epsilon                          # reparameterization trick
        return z
        
                
    def forward(self, x):
        mean, log_var = self.Encoder(x)
        z = self.reparameterization(mean, torch.exp(0.5 * log_var)) # takes exponential function (log var -> var)
        x_hat            = self.Decoder(z)
        
        return x_hat, mean, log_var

encoder = Encoder(input_dim=x_dim, hidden_dim1=hidden_dim1,hidden_dim2=hidden_dim2, latent_dim=latent_dim)
decoder = Decoder(latent_dim=latent_dim, hidden_dim1 = hidden_dim1,hidden_dim2=hidden_dim2, output_dim = x_dim)

# from torch.optim import Adam
# BCE_loss = nn.BCELoss()

# def loss_function(x, x_hat, mean, log_var):
#     # reproduction_loss = nn.functional.binary_cross_entropy(x_hat, x, reduction='sum')
#     reproduction_loss = nn.functional.mse_loss(x_hat, x, reduction='sum')

#     KLD      = - 0.5 * torch.sum(1+ log_var - mean.pow(2) - log_var.exp())
#     w_loss = x.mean() -x_hat.mean() #mean(x,x_hat) # K.mean(y_true * y_pred)

#     return reproduction_loss + KLD + w_loss


# optimizer_VAE = Adam(model.parameters(), lr=lr)

# def vae_train(train_loader):
#   # Training

#   model.train()
#   for epoch in range(epochs):
#       zxmean = torch.zeros(latent_dim,9)
#       train_loss = 0
#       #for batch_idx, (x,x_perm, _) in enumerate(train_loader):
#       for batch_idx, (x, _) in enumerate(train_loader):
#           # x = x.view(dataStream.batchSize, x_dim)
#           # x = x.view(batch_size, 1,52,52)
#           x = x.to(DEVICE)
#           #x_perm = x_perm.view(batch_size, x_dim)
#           #x_perm = x_perm.to(DEVICE)
#           #optimizer_VAE.zero_grad()

#           x_hat, mean, log_var = model(x)
#           loss = loss_function(x, x_hat, mean, log_var)
          
#           train_loss += loss.item()
#           # print(type(train_loss), getsizeof(train_loss))
#           loss.backward()
#           optimizer_VAE.step()
#           optimizer_VAE.zero_grad()

      
#       # model.eval()     # Optional when not using Model Specific layer
#       # valid_loss = 0.0
#       # for batch_idx1, (x_valid,_) in enumerate(valid_loader):

#       #   x_hat, mean, log_var = model(x_valid)
#       #   loss = loss_function(x_valid, x_hat, mean, log_var)

#       #   valid_loss += loss.item()

#       # valid_loss /= (batch_idx1*batch_size)   
#       print("\tEpoch", epoch + 1, "complete!", "\tTraining Loss: ", train_loss / (batch_idx*batch_size),)
